// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVXMU4WNPK5o-6hH5FQqB41iQyeGmG7Lc',
    appId: '1:28107667379:android:7d13b7a182ef0522ef3dc6',
    messagingSenderId: '28107667379',
    projectId: 'hyiplab-b4a93',
    storageBucket: 'hyiplab-b4a93.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChkfediKQ9jI1egAqUOECnSmrBwSwbPmk',
    appId: '1:28107667379:ios:61ceb50a7587abdaef3dc6',
    messagingSenderId: '28107667379',
    projectId: 'hyiplab-b4a93',
    storageBucket: 'hyiplab-b4a93.appspot.com',
    iosBundleId: 'dev.vlab.hyiplab',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFZZHvrYaVmm2SG3Aohx497ee_T7gkgvU',
    appId: '1:28107667379:web:4929c5c330f9d839ef3dc6',
    messagingSenderId: '28107667379',
    projectId: 'hyiplab-b4a93',
    authDomain: 'hyiplab-b4a93.firebaseapp.com',
    storageBucket: 'hyiplab-b4a93.appspot.com',
    measurementId: 'G-FYWRPZT4FB',
  );

}