name: hyip_lab
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.1
  http: ^1.1.0
  flutter_svg: ^2.0.7
  lottie: ^3.1.2
  shared_preferences: ^2.0.13
  flutter_rating_bar: ^4.0.0
  image_picker: ^1.0.4
  file_picker: ^8.0.6
  path_provider: ^2.0.9
  country_picker: ^2.0.11
  intl: ^0.19.0
  pin_code_fields: ^8.0.1
  dio: ^5.3.3
  flutter_widget_from_html_core: ^0.15.1
  qr_code_scanner: ^1.0.0
  dotted_border: ^2.0.0+2
  animated_bottom_navigation_bar: ^1.3.0
  auto_size_text: ^3.0.0
  share_plus: ^10.0.0
  syncfusion_flutter_charts: ^26.2.4
  url_launcher: ^6.0.20
  flutter_widget_from_html: ^0.15.1
  font_awesome_flutter: ^10.2.1
  shimmer: ^3.0.0
  simple_animations: ^5.0.2
  firebase_messaging: ^15.0.4
  flutter_local_notifications: ^17.2.1
  firebase_core: ^3.3.0
  connectivity_plus: ^6.0.3
  firebase_core_platform_interface: ^5.2.0
  percent_indicator: ^4.2.2
  google_fonts: ^6.1.0
  awesome_dialog: ^3.0.2
  dashed_circular_progress_bar: ^0.0.4
  flutter_inappwebview: ^5.8.0
  json_annotation: any
  permission_handler: ^11.3.1
  flutter_spinkit: ^5.2.1
  open_file: ^3.3.2
  google_sign_in: ^6.2.1
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/onboard/
    - assets/images/logo/
    - assets/images/social/
    - assets/images/menu/
    - assets/images/bottom_nav/
    - assets/icons/home_menu_icon/
    - assets/icons/
    - assets/animation/
    - assets/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf

    - family: Lora
      fonts:
        - asset: assets/fonts/Lora-Regular.ttf